if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
	" Appearance
	Plug 'ap/vim-buftabline'
	Plug 'itchyny/lightline.vim'
	Plug 'arcticicestudio/nord-vim'

	" Git
	Plug 'tpope/vim-fugitive'

	" File management
	Plug 'Yggdroot/LeaderF', { 'do': './install.sh' }

	" Snippets
	Plug 'SirVer/ultisnips'

	" Languages
	Plug 'lervag/vimtex'
	Plug 'KeitaNakamura/tex-conceal.vim'
call plug#end()

" --- Vim

" Line numbers
set number relativenumber

" Escape timeout length
set timeoutlen=200

" Allow to switch away from unsaved buffer
set hidden

" Buffer switch mappings
nnoremap <BS> :b #<CR>
nnoremap <C-d> :bp<CR>
nnoremap <C-a> :bn<CR>

" Leaders
let mapleader=','
let maplocalleader=','



" Tab settings:
" Use 'real' tabs with size 4, treat consecutive spaces like tabs for deletion
set tabstop=4
set shiftwidth=4
set softtabstop=4
set noexpandtab

set listchars=tab:>~ list

" Cursor distance from edge
set scrolloff=10

" Line length and paragraph formatting
set textwidth=80
set formatoptions=rq

" Colorscheme
colorscheme nord

" Backspace

set backspace=indent,eol,start


" --- Buftabline

let g:buftabline_numbers = 2
let g:buftabline_indicators = 1

" --- Lightline

set laststatus=2
let g:lightline = {
		\ 'colorscheme': 'wombat',
		\ 'active': {
			\ 'left': [['mode', 'paste'], ['readonly', 'filename', 'modified']],
			\ 'right': [
				\ ['lineinfo', 'percent'],
				\ ['fileformat', 'fileencoding', 'filetype'],
				\ ['gitbranch']
			\ ],
		\ },
		\ 'component_function': {
			\ 'gitbranch': 'fugitive#head',
		\ },
	\ }

" --- LeaderF

nnoremap <C-p> :Leaderf file <CR>
nnoremap <C-t> :Leaderf tag <CR>

" --- Ultisnips

let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'

let g:UltiSnipsSnippetsDir = 'UltiSnips'

" --- Vimtex

let g:tex_flavor='latex'
let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0
let conceallevel=2
let g:tex_conceal='abdmg'
