if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
	" Appearance
	Plug 'ap/vim-buftabline'
	Plug 'itchyny/lightline.vim'
	Plug 'arcticicestudio/nord-vim'

	" Git
	Plug 'tpope/vim-fugitive'

	" File management
	Plug 'Yggdroot/LeaderF' " , { 'do': './install.sh' } Cannot enable this; building in NixOS is apparently weird
call plug#end()

" --- Vim

" Line numbers
set number relativenumber

" Escape timeout length
set timeoutlen=200

" Allow to change away from unsaved buffer
set hidden

" Buffer switch mappings
nnoremap <BS> :b #<CR>
nnoremap <C-q> :bp<CR>
nnoremap <C-e> :bn<CR>

" Tab settings
set tabstop=4
set shiftwidth=4
set softtabstop=4
set noexpandtab

" Cursor distance from edge
set scrolloff=10

" Line length and paragraph formatting
set textwidth=100
set formatoptions=rq

" Colorscheme
colorscheme nord


" Command command

function ExecuteCommand(command)
	enew

	setlocal buftype=nofile bufhidden=hide noswapfile

	if !bufexists(a:command)
		" Reset main filename to overwrite it
		silent 0file
		silent execute 'file' a:command
	else
		" TODO open with alternate name
		echoerr 'Command buffer still open'
		bdelete
		return
	endif

	" TODO execute async?
    silent execute '%!' a:command

	return
endfunction

command -nargs=* Exec :call ExecuteCommand('<args>')
command -nargs=* E :Exec <args>


" --- Buftabline

let g:buftabline_numbers = 2
let g:buftabline_indicators = 1

" --- Lightline

set laststatus=2
let g:lightline = {
            \ 'colorscheme': 'wombat',
            \ 'active': {
            \   'left': [['mode', 'paste'], ['readonly', 'filename', 'modified']],
            \   'right': [['lineinfo', 'percent'], ['fileformat', 'fileencoding', 'filetype'], ['gitbranch']],
            \ },
            \ 'component_function': {
            \   'gitbranch': 'fugitive#head',
            \ },
            \ }

" --- LeaderF

nnoremap <C-p> :Leaderf file <CR>
nnoremap <C-t> :Leaderf tag <CR>
